### ISSUE TITLE
[Bug]: Layout issue with latest Mushroom update.

### ISSUE THREAD

**Issue by wishie** [ulic75/lovelace-mushroom#15]
### Current Behavior

![168468518-adfce504-9cec-4bc6-a555-57e6219c2d4c](https://user-images.githubusercontent.com/635844/168471965-094386da-696d-412d-9239-ce2e4c13c861.png)
![168468513-d960f64a-80ac-4e1a-8588-afab5a71afa2](https://user-images.githubusercontent.com/635844/168471967-e3a36e00-28cf-41bc-893d-2348897353be.png)

### Environment

```markdown
- OS:
- Node:
- Version:
- Hassio:
```

**Comment by ulic75** [comment]
Are you running the latest version of the thermostat card? v1.8.3-thermostat.1

**Comment by wishie** [comment]
HACS is only offering up 1.7.3-thermostat.2

**Comment by wishie** [comment]
Manually updated, and now its fine.. although there is some kind of shadow now
![Screen Shot 2022-05-16 at 8 46 18 am](https://user-images.githubusercontent.com/635844/168497193-90473015-948e-4b98-a0ec-dea26fc8f64b.png)
.

**Comment by ulic75** [comment]
Do you not see shadows in other mushroom cards? All mine have a shadow (mostly visible to me in light mode).

**Comment by wishie** [comment]
Perhaps I have not noticed them.. I will check again.
![Screen Shot 2022-05-16 at 10 13 23 am](https://user-images.githubusercontent.com/635844/168500639-446a665c-7846-4499-a5a5-6df3451aa0d9.png)
![Screen Shot 2022-05-16 at 10 13 13 am](https://user-images.githubusercontent.com/635844/168500644-f573a1ea-9643-4e27-afa9-d656ecd84e34.png)
![Screen Shot 2022-05-16 at 10 12 56 am](https://user-images.githubusercontent.com/635844/168500645-d1e1df71-d0d4-4d69-a40a-9793b01ffddb.png)

**Comment by ulic75** [comment]
Ah I zoomed in on your screenshot and see what your describing.  I'm not seeing the same issue however. It looks like the thermostat card is nested in another card.

![Screenshot_20220515-194831](https://user-images.githubusercontent.com/5641964/168506782-13286d77-2c5a-4616-8743-5c6ecfb0cad5.png)

P.S. You should probably close https://github.com/piitaya/lovelace-mushroom/issues/485

**Comment by wishie** [comment]
It is not nested inside another card, but I also can't reproduce the issue on other PCs or apps.. I will investigate a bit more

________________________________

**Comment by wishie** [comment]
It was only happening on the Home Assistant Companion App for macOS and forcefully resetting the app appears to have fixed it.
