### ISSUE TITLE
[Bug]: HVAC state not visible in text & icon

### ISSUE THREAD

**Issue by timvdsm** [ulic75/lovelace-mushroom#16]
### Current Behavior

Hi,
First of all thanks for your nice work.
Matches perfect with the mushroom cards :-)

The icon action/state is correct for me when hvac_action is cooling (blue snowflake icon) & hvac_action is heating (orange fire icon). Thats's working perfect! However when the hvac_action is idle, then it gives a grey thermostat icon. 

For my understanding: the state (mode) of the climate entity is cool/heat/off, so that should define the icons (snowflake, fire, thermostat). 
Then the hvac_action defines cooling, heating, idle. This should match the color: cooling: blue, heating: orange, idle: grey. 
Does that sound logical to you? 
So for example, you could have a mode: cool & hvac_action: idle --> icon: grey snowflake. When you have mode: cool & hvac_action: cooling --> icon: blue snowflake. 

Now I see it like this (in my understanding it should have had a grey fire icon because the mode is "heat" and the hvac_action is "idle"):
<img width="393" alt="Schermafbeelding 2022-05-25 om 16 00 22" src="https://user-images.githubusercontent.com/14946020/170280819-59e4cc43-8252-49b0-94a6-26827c700150.png">

And would it also be possible to add the climate state text next to the hvac_action?
Would be great to see in the text: Inactive - Heat - auto
First: hvac_action (heating, cooling, idle)
Second: state of climate (cool, heat, off)
Third: preset (auto for me)

Like that it's also mentioned in the standard climate entity:
<img width="382" alt="Schermafbeelding 2022-05-25 om 16 00 31" src="https://user-images.githubusercontent.com/14946020/170280870-b93c7d04-d5bd-4fca-9a70-fffc8cfc04c2.png">

Many thanks!

### Environment

```markdown
- OS:HA OS 8.1
- Node:
- Version: Core 2022.5.5
- Hassio:
```

**Comment by ulic75** [comment]
> For my understanding: the state (mode) of the climate entity is cool/heat/off, so that should define the icons (snowflake, fire, thermostat). Then the hvac_action defines cooling, heating, idle. This should match the color: cooling: blue, heating: orange, idle: grey. Does that sound logical to you? So for example, you could have a mode: cool & hvac_action: idle --> icon: grey snowflake. When you have mode: cool & hvac_action: cooling --> icon: blue snowflake.
> 
> Now I see it like this (in my understanding it should have had a grey fire icon because the mode is "heat" and the hvac_action is "idle")

I understand what you are saying.  Let me provide some further clarity as to how it's actually design.  Currently it's designed to show the action icon if your device supports the hvac_action attribute (not all do) else it shows the state icon.  The part in your suggestion that doesn't work (or at least that I'm not fond of) is when you have a device that supports auto or heat/cool mode.  In that mode currently it displays the thermostat icon and changes to the hvac_action icon if available.  With what describe the auto or heat/cool icon would be displayed always and just the color would change.

I'm not sure one way is better than the other, but I'm also not sure what might be better than either of them.

P.S.  The action, stat/mode, preset string was implemented in #18, but has not yet been released as I ponder your other suggestion.

**Comment by timvdsm** [comment]
> Let me provide some further clarity as to how it's actually design.
Many thanks for clarification 👍 

> Currently it's designed to show the action icon if your device supports the hvac_action attribute (not all do) else it shows the state icon.
Absolutely great you thought about that. It's a really nice feature. Indeed, I have 1 climate entity which doesn't have the hvac_action and it nicely showed the icon and colors. I would absolutely keep that. 

> The part in your suggestion that doesn't work (or at least that I'm not fond of) is when you have a device that supports auto or heat/cool mode.
You're totally right on that :-). I didn't take that into account. 
Would it be an idea (don't know if it's technically difficult or not) that in case there is an "auto" or "heat/cool" mode active that you set the icon and color depending on the hvac_action? And in case there is another mode active than "auto" or "heat/cool" (for example heat, cool or off) it takes the icon from the mode and the color from hvac_action?

**Comment by LucaOverflow** [comment]
Hey there,
Thank you for your great Work. I'm not quite sure if this is related or if I should open a new Issue.
When I set my Thermostats on Auto there is no visualization for the set Temperature.

In heating mode it looks as it should like this:
<img width="391" alt="Bildschirmfoto 2022-05-28 um 02 57 36" src="https://user-images.githubusercontent.com/44546543/170803476-fc164e48-b45f-4091-9627-e9a3556661df.png">

This is how it looks in Auto:
<img width="385" alt="Bildschirmfoto 2022-05-28 um 02 59 03" src="https://user-images.githubusercontent.com/44546543/170803522-e5c83044-dcd7-4c77-90b4-f7b0b850a393.png">

**Comment by ulic75** [comment]
@LucaOverflow Yes, please open a new issue if you don't mind.  Also include a screen shot of your device from the developer tools, so I can see the state and attributes when it's not functioning correctly.

**Comment by ulic75** [comment]
These issues have been resolved in v1.8.8-thermostat.0
