### ISSUE TITLE
[Feature]: Temp Slider colour to match mode colour

### ISSUE THREAD

**Issue by ciedema** [ulic75/lovelace-mushroom#25]
### Is your feature request related to a problem?

Currently the temperature slider colour is blue.

### Describe the solution you'd like

It would be great to have the colour of the slider match the mode.  i.e. Orange for heat, Blue for Cool etc.

**Comment by ulic75** [comment]
It should support that feature.  This could possibly be due to a bug that was introduced in #20.  Please confirm if the issue still exists in the next release when the fix (#24) is included.

**Comment by ciedema** [comment]
Hi - this appears to be resolved.  Thanks heaps - really is an excellent complement to a great package.
