### ISSUE TITLE
Temperature is not displayed and controls are not working.

### ISSUE THREAD

**Issue by fanningert** [ulic75/lovelace-mushroom#3]
**Describe the bug**
Temperature is not displayed and controls are not working.

Home Assistant 2022.4.5
Mushroom Cards 1.6.2
Mushroom - Thermostat v1.6.2-thermostat.0

**Screenshots**
![image](https://user-images.githubusercontent.com/365219/164799725-a8b1a35b-5552-49ce-8742-cb6e7eb5bb0e.png)

**Additional context**

**Comment by fanningert** [comment]
Here are also the errors of the browser developer tools.
![image](https://user-images.githubusercontent.com/365219/164801331-dfcf10c1-d5d7-460c-bb18-610baf0999e1.png)

**Comment by fanningert** [comment]
Here are also the information about the entity.
![image](https://user-images.githubusercontent.com/365219/164885375-5dc9ac16-f331-4e23-a28a-a4fefde692c4.png)

**Comment by jhbruhn** [comment]
For me this is an issue with the way number formatting is selected. The imperial(?) way of 123,456.78 results in a correctly rendered temperature, but when I set it to 123.456,78 for, in my case, German locale, the card displays NaN.

**Comment by ulic75** [comment]
Huh, I seem to have not been notified about these issues.  My apologies.

Closed by #7
