### ISSUE TITLE
Can't turn on the climate using the slider 

### ISSUE THREAD

**Issue by Schluggi** [ulic75/lovelace-mushroom#4]
**Describe the bug**

**To Reproduce**
1. Activate the slider for the card
2. Turn off the climate 
3. Click on the slider to set a temperature
4. Nothing happens

**Expected behavior**
I would to expect the climate to turn on and set to the selected temperature. Otherwise there is no option to turn the climate on again. 
This would be analog to the other mushroom cards. For example I can turn on a light by using the slider only. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Any
 - Browser: Tested with Firefox 90 and Chromium 100.0.4896.88

**Smartphone (please complete the following information):**
 - Device: OnePlus7 
 - OS: Android 11
 - Browser: Firefox and HA-App
 - Version: Latest

**Comment by Schluggi** [comment]
At least for my homematic thermostats there is currently no way to turn it on using your card. The on/off button turns the climate only off, not on.

My workaround for that is an on-click service call. But that's feels really dirty.

**Comment by ulic75** [comment]
Have you tried it with the stock Thermostat card provided by HA?  Does it work as you expect?

**Comment by Schluggi** [comment]
> Have you tried it with the stock Thermostat card provided by HA? Does it work as you expect? Can you send a link to the product you're using?

Yes. I've used the HA card before. The on/off button turns only off the thermostat. To turn it on again I have to set a temperature.

Here the Product I'm using. Homematic is really popular in Germany: 
https://en.homematic-ip.com/en/products/detail/homematic-ip-radiator-thermostat.html
